@startuml
title Admin Activity

|Application|
start
:Open App;

|Application|
:Check if user is logged in?;

if (User is logged in?) then (yes)
else (no)
  |Telegram|
  :Authenticate with Telegram;
  :Telegram verifies credentials;

  |System|
  :Verify login credentials;
end if

|Application|
:List Discount Codes;
:Create Discount Code;
:Edit Discount Code;
:List Users;

stop
@enduml
